# Generated by Django 5.2.3 on 2025-06-13 22:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('title', models.CharField(max_length=50)),
                ('minimum_expreience', models.PositiveIntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Role',
                'verbose_name_plural': 'Job Roles',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['title'], name='analyzer_jo_title_ab7b26_idx')],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('resume', models.FileField(upload_to='resumes/')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('github', models.URLField(blank=True, null=True)),
                ('total_experience', models.FloatField(blank=True, default=0.0)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('verdict', models.CharField(blank=True, choices=[('matched', 'Matched'), ('skipped', 'Skipped'), ('overqualified', 'Overqualified')], max_length=15)),
                ('matched_mandatory_skills', models.JSONField(blank=True, null=True)),
                ('missed_mandatory_skills', models.JSONField(blank=True, null=True)),
                ('matched_optional_skills', models.JSONField(blank=True, null=True)),
                ('missed_optional_skills', models.JSONField(blank=True, null=True)),
                ('experiences', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.jobrole')),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('title', models.CharField(max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['title'], name='analyzer_sk_title_417b43_idx')],
            },
        ),
        migrations.CreateModel(
            name='SkillRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mandatory', models.BooleanField(default=True)),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_requirements', to='analyzer.jobrole')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.skill')),
            ],
            options={
                'verbose_name': 'Skill Requirement',
                'verbose_name_plural': 'Skill Requirements',
                'unique_together': {('job_role', 'skill')},
            },
        ),
    ]
