# Generated by Django 5.2.3 on 2025-06-13 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_rename_github_resume_githubb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='githubb',
            new_name='github',
        ),
    ]
