# Generated by Django 5.2.4 on 2025-07-13 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0006_jobrole_active_jobrole_version'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skillrequirements',
            unique_together=set(),
        ),
    ]
