# Generated by Django 5.2.4 on 2025-07-13 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0007_alter_skillrequirements_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrole',
            name='version',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='skillrequirements',
            unique_together={('job_role', 'skill')},
        ),
    ]
