# Generated by Django 5.2.4 on 2025-07-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0008_alter_jobrole_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='verdict',
            field=models.CharField(blank=True, choices=[('matched', 'Matched'), ('skipped', 'Skipped'), ('overqualified', 'Overqualified')], default='matched', max_length=15),
        ),
    ]
