# Generated by Django 5.2.4 on 2026-07-09 12:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0014_resume_educations'),
    ]

    def create_postings_from_roles(apps, schema_editor):
        JobRole = apps.get_model('analyzer', 'JobRole')
        JobPosting = apps.get_model('analyzer', 'JobPosting')

        for role in JobRole.objects.all().iterator():
            JobPosting.objects.update_or_create(
                id=role.id,
                defaults={
                    'role_id': role.id,
                    'title_override': '',
                    'department': '',
                    'location': '',
                    'required_experience': getattr(role, 'minimum_experience', 0) or 0,
                    'status': 'open' if getattr(role, 'active', True) else 'closed',
                },
            )

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_override', models.CharField(blank=True, max_length=120)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('required_experience', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postings', to='analyzer.jobrole')),
            ],
            options={
                'verbose_name': 'Job Posting',
                'verbose_name_plural': 'Job Postings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(create_postings_from_roles, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='resume',
            name='job_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='analyzer.jobposting'),
        ),
        migrations.AlterField(
            model_name='skillrequirements',
            name='job_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_requirements', to='analyzer.jobposting'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['status'], name='analyzer_jo_status_2f4950_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['created_at'], name='analyzer_jo_created_33895b_idx'),
        ),
    ]
