# Generated by Django 5.2.4 on 2026-07-09 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0015_jobposting_alter_resume_job_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrole',
            name='active',
        ),
        migrations.RemoveField(
            model_name='jobrole',
            name='minimum_experience',
        ),
        migrations.RemoveField(
            model_name='jobrole',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='jobrole',
            name='version',
        ),
    ]
