# Generated by Codex on 2026-07-10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0016_remove_jobrole_active_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobRole',
            new_name='Position',
        ),
    ]
