# Generated by Codex on 2026-07-10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0017_rename_jobrole_to_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobposting',
            old_name='role',
            new_name='position',
        ),
    ]
