# Generated by Codex on 2026-07-10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0018_rename_jobposting_role_to_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobposting',
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
            },
        ),
        migrations.AlterModelOptions(
            name='position',
            options={
                'ordering': ['title'],
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
            },
        ),
        migrations.RenameIndex(
            model_name='position',
            new_name='analyzer_po_title_05a2d0_idx',
            old_name='analyzer_jo_title_ab7b26_idx',
        ),
    ]
