# Generated by Codex on 2026-07-11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0019_alter_jobposting_options_alter_position_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='job_role',
            new_name='job_posting',
        ),
        migrations.RenameField(
            model_name='skillrequirements',
            old_name='job_role',
            new_name='job_posting',
        ),
    ]
