# Generated by Codex on 2026-07-11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0020_rename_job_role_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillrequirements',
            options={
                'ordering': ['job_posting', 'skill'],
                'unique_together': {('job_posting', 'skill')},
                'verbose_name': 'Skill Requirement',
                'verbose_name_plural': 'Skill Requirements',
            },
        ),
    ]
